In [113]:
import numpy as np

rand_score = 60 + 40*np.random.rand (20,3)
rand_score = rand_score.astype (int)

print (rand_score)


[[79 73 99]
 [68 60 78]
 [88 75 65]
 [92 79 78]
 [70 97 88]
 [60 70 75]
 [74 68 68]
 [90 70 72]
 [92 71 92]
 [74 73 71]
 [91 64 89]
 [92 98 69]
 [94 74 79]
 [90 60 69]
 [69 71 69]
 [70 80 66]
 [98 70 69]
 [61 81 93]
 [68 76 61]
 [85 84 83]]


In [114]:
# Q1 

# a)
ave_column = np.mean (rand_score, axis=0)
ave_row = np.mean (rand_score, axis=1)
print (ave_column)
print (ave_row)



[80.25 74.7  76.65]
[83.66666667 68.66666667 76.         83.         85.         68.33333333
 70.         77.33333333 85.         72.66666667 81.33333333 86.33333333
 82.33333333 73.         69.66666667 72.         79.         78.33333333
 68.33333333 84.        ]


In [115]:
# b)
max_score = np.max (rand_score, axis=0)
min_score = np.min (rand_score, axis=0)
print (min_score)

[60 60 61]


In [116]:
# c)
ave_first_two = np.mean (rand_score[0:2], axis=1)
ave_last_two = np.mean (rand_score[18:20], axis=1)

print (ave_first_two)
print (ave_last_two)

[83.66666667 68.66666667]
[68.33333333 84.        ]


In [117]:
# d)
ave_Mid_first10 = np.mean (rand_score[0:10,0:2], axis=1)
print (ave_Mid_first10)

[76.  64.  81.5 85.5 83.5 65.  71.  80.  81.5 73.5]


In [118]:
# e)
import collections
list_70 = np.where (rand_score < 70)
row_number = np.unique(list_70[0])
print ('Students row are:',row_number)

rand_score[rand_score <70] = 70

alt_student = []

for i in (row_number):
    alt_student.append (rand_score[i,0:3:2])

alt_student = np.array(alt_student)
ave_alt = np.mean (alt_student,axis=0)

print (ave_alt)

Students row are: [ 1  2  5  6 10 11 13 14 15 16 17 18]
[79.41666667 74.58333333]


In [119]:
# f)
weight_matrix = np.zeros((3,3))
np.fill_diagonal (weight_matrix,[0.3,0.3,0.4])

sum_total_10 = np.dot(rand_score[0:10], weight_matrix).sum(axis=1)

print (sum_total_10)


[85.2 73.2 76.9 82.5 85.3 72.  71.2 76.8 85.7 72.5]


In [120]:
# g)

weight_matrix = np.zeros((3,3))
np.fill_diagonal (weight_matrix,[1.1, 1.1, 0.95])
upodated_total = np.dot(rand_score, weight_matrix)

print (upodated_total)

[[ 86.9   80.3   94.05]
 [ 77.    77.    74.1 ]
 [ 96.8   82.5   66.5 ]
 [101.2   86.9   74.1 ]
 [ 77.   106.7   83.6 ]
 [ 77.    77.    71.25]
 [ 81.4   77.    66.5 ]
 [ 99.    77.    68.4 ]
 [101.2   78.1   87.4 ]
 [ 81.4   80.3   67.45]
 [100.1   77.    84.55]
 [101.2  107.8   66.5 ]
 [103.4   81.4   75.05]
 [ 99.    77.    66.5 ]
 [ 77.    78.1   66.5 ]
 [ 77.    88.    66.5 ]
 [107.8   77.    66.5 ]
 [ 77.    89.1   88.35]
 [ 77.    83.6   66.5 ]
 [ 93.5   92.4   78.85]]
