In [1032]:
import numpy as np

rand_score = 60 + 40*np.random.rand (20,3)
rand_score = rand_score.astype (int)

print (rand_score)


[[64 92 65]
 [60 72 85]
 [70 65 80]
 [75 77 71]
 [99 67 99]
 [75 98 79]
 [95 88 69]
 [62 82 81]
 [88 64 65]
 [67 68 90]
 [93 94 64]
 [66 95 72]
 [88 93 92]
 [81 71 66]
 [82 75 74]
 [78 65 69]
 [83 85 85]
 [83 97 85]
 [72 74 65]
 [65 83 62]]


In [1033]:
# Question 1

# a)
ave_column = np.mean (rand_score, axis=0)
ave_row = np.mean (rand_score, axis=1)
print (ave_column)
print (ave_row)

[77.3  80.25 75.9 ]
[73.66666667 72.33333333 71.66666667 74.33333333 88.33333333 84.
 84.         75.         72.33333333 75.         83.66666667 77.66666667
 91.         72.66666667 77.         70.66666667 84.33333333 88.33333333
 70.33333333 70.        ]


In [1034]:
# b)
max_score = np.max (rand_score, axis=0)
min_score = np.min (rand_score, axis=0)
print (min_score)

[60 64 62]


In [1035]:
# c)
ave_first_two = np.mean (rand_score[0:2], axis=1)
ave_last_two = np.mean (rand_score[18:20], axis=1)

print (ave_first_two)
print (ave_last_two)

[73.66666667 72.33333333]
[70.33333333 70.        ]


In [1036]:
# d)
ave_Mid_first10 = np.mean (rand_score[0:10,0:2], axis=1)
print (ave_Mid_first10)

[78.  66.  67.5 76.  83.  86.5 91.5 72.  76.  67.5]


In [1037]:
# e)
import collections
list_70 = np.where (rand_score < 70)
row_number = np.unique(list_70[0])
print ('Students row are:',row_number)

rand_score[rand_score <70] = 70

alt_student = []

for i in (row_number):
    alt_student.append (rand_score[i,0:3:2])

alt_student = np.array(alt_student)
ave_alt = np.mean (alt_student,axis=0)

print (ave_alt)

Students row are: [ 0  1  2  4  6  7  8  9 10 11 13 15 18 19]
[78.28571429 76.21428571]


In [1038]:
# f)
weight_matrix = np.zeros((3,3))
np.fill_diagonal (weight_matrix,[0.3,0.3,0.4])

sum_total_10 = np.dot(rand_score[0:10], weight_matrix).sum(axis=1)

print (sum_total_10)

[76.6 76.6 74.  74.  90.3 83.5 82.9 78.  75.4 78. ]


In [1039]:
# g)

weight_matrix = np.zeros((3,3))
np.fill_diagonal (weight_matrix,[1.1, 1.1, 0.95])
upodated_total = np.dot(rand_score, weight_matrix)

print (upodated_total)

[[ 77.   101.2   66.5 ]
 [ 77.    79.2   80.75]
 [ 77.    77.    76.  ]
 [ 82.5   84.7   67.45]
 [108.9   77.    94.05]
 [ 82.5  107.8   75.05]
 [104.5   96.8   66.5 ]
 [ 77.    90.2   76.95]
 [ 96.8   77.    66.5 ]
 [ 77.    77.    85.5 ]
 [102.3  103.4   66.5 ]
 [ 77.   104.5   68.4 ]
 [ 96.8  102.3   87.4 ]
 [ 89.1   78.1   66.5 ]
 [ 90.2   82.5   70.3 ]
 [ 85.8   77.    66.5 ]
 [ 91.3   93.5   80.75]
 [ 91.3  106.7   80.75]
 [ 79.2   81.4   66.5 ]
 [ 77.    91.3   66.5 ]]


In [1040]:
# Question 2
# a)

def median_and_mode (x):
    median = np.median (x)
    
    mode = np.bincount(x.flat).argmax()

    print ('Median is:', median)
    print ('Mode is:', mode)


In [1041]:
# b)

x1 = np.array ([[1,2,2,2,3,5],[2,4,2,2,7,8]])
x2 = np.array ([[1,1,3],[3,3,7],[8,8,7]])
x3 = np.array ([[2,3,3,3,3], [1,4,4,5,8], [3,4,6,3,5],[3,3,6,6,11]])

median_and_mode (x1)
median_and_mode (x2)
median_and_mode (x3)

Median is: 2.0
Mode is: 2
Median is: 3.0
Mode is: 3
Median is: 3.5
Mode is: 3


In [1042]:
# c)
def median_and_mode_axis (x, axis):
    if axis == "row":
        for i in range (x.shape[0]):
            median = np.median (x[i])
            print ('Median in row',i, 'is:', median)
            mode = np.bincount(x[i]).argmax()
            print ('Mode in row',i, 'is:', mode)
        
    if axis == "column":
        for i in range (x.shape[1]):
            median = np.median (x[:,i])
            print ('Median in column',i, 'is:', median)
            mode = np.bincount(x[:,i]).argmax()
            print ('Mode in column',i, 'is:', mode)




In [1043]:
median_and_mode_axis(x2, axis='row')

Median in row 0 is: 1.0
Mode in row 0 is: 1
Median in row 1 is: 3.0
Mode in row 1 is: 3
Median in row 2 is: 8.0
Mode in row 2 is: 8


In [1044]:
median_and_mode_axis(x2, axis='column')

Median in column 0 is: 3.0
Mode in column 0 is: 1
Median in column 1 is: 3.0
Mode in column 1 is: 1
Median in column 2 is: 7.0
Mode in column 2 is: 7


In [1063]:
# Question 3

empty_matrix = np.array ([['?','?','?'],['?','?','?'],['?','?','?']])

steps = 0

def TTT_game (x, y):
    
    global steps
    if steps ==8:
        print ('Draw')
        
    if (steps%2) ==0:
        if empty_matrix [x][y] == '?':
            empty_matrix [x][y] = 'X'
            steps+=1
            print (empty_matrix)

            for i in range (3):
                if np.sum (np.char.count(empty_matrix[i], 'X')) ==3 or np.sum (np.char.count(empty_matrix[:,i], 'X')) ==3 or np.sum (np.char.count(np.diag(empty_matrix), 'X')) ==3 or np.sum (np.char.count(np.diag(np.fliplr(empty_matrix)),'X')) ==3:
                    print ('First Player Win, Start New One')
                    
            else:   print ('No One Win, Continue Please')
        else:
            print ('Try Another Place')


    else:
        if empty_matrix[x][y] == '?':
            empty_matrix[x][y] = 'O'
            steps+=1
            print (empty_matrix)

            for i in range (3):
                if np.sum (np.char.count(empty_matrix[i], 'O')) == 3 or np.sum (np.char.count(empty_matrix[:,i], 'O')) == 3 or np.sum (np.char.count(np.diag(empty_matrix), 'O')) == 3 or np.sum (np.char.count(np.diag(np.fliplr(empty_matrix)),'O')) ==3:
                    print ('Second Player Win, Start New One')
                    
            else:   print ('No One Win, Continue Please')
        else:
            print ('Try Another Place')


  

In [1064]:
print (empty_matrix)

[['?' '?' '?']
 ['?' '?' '?']
 ['?' '?' '?']]


In [1065]:
TTT_game (1,1)

[['?' '?' '?']
 ['?' 'X' '?']
 ['?' '?' '?']]
No One Win, Continue Please


In [1066]:
TTT_game (0,0)

[['O' '?' '?']
 ['?' 'X' '?']
 ['?' '?' '?']]
No One Win, Continue Please
