In [99]:
import numpy as np

rand_score = 60 + 40*np.random.rand (20,3)
rand_score = rand_score.astype (int)

print (rand_score)


[[74 68 65]
 [76 64 94]
 [85 65 94]
 [86 97 60]
 [66 62 86]
 [73 75 65]
 [96 87 70]
 [65 73 61]
 [86 92 79]
 [65 65 95]
 [61 79 82]
 [81 62 88]
 [78 67 74]
 [99 90 73]
 [84 91 65]
 [69 89 73]
 [61 64 82]
 [62 92 79]
 [62 66 83]
 [85 98 82]]


In [100]:
# Question 1

# a)
ave_column = np.mean (rand_score, axis=0)
ave_row = np.mean (rand_score, axis=1)
print (ave_column)
print (ave_row)

[75.7 77.3 77.5]
[69.         78.         81.33333333 81.         71.33333333 71.
 84.33333333 66.33333333 85.66666667 75.         74.         77.
 73.         87.33333333 80.         77.         69.         77.66666667
 70.33333333 88.33333333]


In [101]:
# b)
max_score = np.max (rand_score, axis=0)
min_score = np.min (rand_score, axis=0)
print (min_score)

[61 62 60]


In [102]:
# c)
ave_first_two = np.mean (rand_score[0:2], axis=1)
ave_last_two = np.mean (rand_score[18:20], axis=1)

print (ave_first_two)
print (ave_last_two)

[69. 78.]
[70.33333333 88.33333333]


In [103]:
# d)
ave_Mid_first10 = np.mean (rand_score[0:10,0:2], axis=1)
print (ave_Mid_first10)

[71.  70.  75.  91.5 64.  74.  91.5 69.  89.  65. ]


In [104]:
# e)
import collections
list_70 = np.where (rand_score < 70)
row_number = np.unique(list_70[0])
print ('Students row are:',row_number)

rand_score[rand_score <70] = 70

alt_student = []

for i in (row_number):
    alt_student.append (rand_score[i,0:3:2])

alt_student = np.array(alt_student)
ave_alt = np.mean (alt_student,axis=0)

print (ave_alt)

Students row are: [ 0  1  2  3  4  5  7  9 10 11 12 14 15 16 17 18]
[74.8125 80.    ]


In [105]:
# f)
weight_matrix = np.zeros((3,3))
np.fill_diagonal (weight_matrix,[0.3,0.3,0.4])

sum_total_10 = np.dot(rand_score[0:10], weight_matrix).sum(axis=1)

print (sum_total_10)

[71.2 81.4 84.1 82.9 76.4 72.4 82.9 70.9 85.  80. ]


In [106]:
# g)

weight_matrix = np.zeros((3,3))
np.fill_diagonal (weight_matrix,[1.1, 1.1, 0.95])
upodated_total = np.dot(rand_score, weight_matrix)

print (upodated_total)

[[ 81.4   77.    66.5 ]
 [ 83.6   77.    89.3 ]
 [ 93.5   77.    89.3 ]
 [ 94.6  106.7   66.5 ]
 [ 77.    77.    81.7 ]
 [ 80.3   82.5   66.5 ]
 [105.6   95.7   66.5 ]
 [ 77.    80.3   66.5 ]
 [ 94.6  101.2   75.05]
 [ 77.    77.    90.25]
 [ 77.    86.9   77.9 ]
 [ 89.1   77.    83.6 ]
 [ 85.8   77.    70.3 ]
 [108.9   99.    69.35]
 [ 92.4  100.1   66.5 ]
 [ 77.    97.9   69.35]
 [ 77.    77.    77.9 ]
 [ 77.   101.2   75.05]
 [ 77.    77.    78.85]
 [ 93.5  107.8   77.9 ]]


In [107]:
# Question 2
# a)

def median_and_mode (x):
    median = np.median (x)
    
    mode = np.bincount(x.flat).argmax()

    print ('Median is:', median)
    print ('Mode is:', mode)


In [108]:
# b)

x1 = np.array ([[1,2,2,2,3,5],[2,4,2,2,7,8]])
x2 = np.array ([[1,3,3],[3,3,7],[8,7,10]])
x3 = np.array ([[2,3,3,3,3], [1,4,7,5,8], [3,4,6,2,5],[3,3,3,6,11]])

median_and_mode (x1)
median_and_mode (x2)
median_and_mode (x3)

Median is: 2.0
Mode is: 2
Median is: 3.0
Mode is: 3
Median is: 3.0
Mode is: 3


In [ ]:
asddd