In [16]:
import numpy as np

rand_score = 60 + 40*np.random.rand (20,3)
rand_score = rand_score.astype (int)

print (rand_score)


[[88 78 61]
 [92 77 71]
 [87 68 65]
 [75 65 64]
 [62 93 82]
 [87 75 92]
 [81 93 79]
 [79 68 73]
 [79 88 94]
 [64 72 73]
 [93 70 78]
 [98 74 98]
 [66 74 96]
 [75 94 66]
 [76 94 72]
 [66 83 77]
 [79 77 72]
 [84 90 61]
 [70 93 72]
 [77 90 84]]


In [17]:
# Question 1

# a)
ave_column = np.mean (rand_score, axis=0)
ave_row = np.mean (rand_score, axis=1)
print (ave_column)
print (ave_row)

[78.9 80.8 76.5]
[75.66666667 80.         73.33333333 68.         79.         84.66666667
 84.33333333 73.33333333 87.         69.66666667 80.33333333 90.
 78.66666667 78.33333333 80.66666667 75.33333333 76.         78.33333333
 78.33333333 83.66666667]


In [18]:
# b)
max_score = np.max (rand_score, axis=0)
min_score = np.min (rand_score, axis=0)
print (min_score)

[62 65 61]


In [19]:
# c)
ave_first_two = np.mean (rand_score[0:2], axis=1)
ave_last_two = np.mean (rand_score[18:20], axis=1)

print (ave_first_two)
print (ave_last_two)

[75.66666667 80.        ]
[78.33333333 83.66666667]


In [20]:
# d)
ave_Mid_first10 = np.mean (rand_score[0:10,0:2], axis=1)
print (ave_Mid_first10)

[83.  84.5 77.5 70.  77.5 81.  87.  73.5 83.5 68. ]


In [21]:
# e)
import collections
list_70 = np.where (rand_score < 70)
row_number = np.unique(list_70[0])
print ('Students row are:',row_number)

rand_score[rand_score <70] = 70

alt_student = []

for i in (row_number):
    alt_student.append (rand_score[i,0:3:2])

alt_student = np.array(alt_student)
ave_alt = np.mean (alt_student,axis=0)

print (ave_alt)

Students row are: [ 0  2  3  4  7  9 12 13 15 17]
[76.8 75.1]


In [22]:
# f)
weight_matrix = np.zeros((3,3))
np.fill_diagonal (weight_matrix,[0.3,0.3,0.4])

sum_total_10 = np.dot(rand_score[0:10], weight_matrix).sum(axis=1)

print (sum_total_10)

[77.8 79.1 75.1 71.5 81.7 85.4 83.8 73.9 87.7 71.8]


In [23]:
# g)

weight_matrix = np.zeros((3,3))
np.fill_diagonal (weight_matrix,[1.1, 1.1, 0.95])
upodated_total = np.dot(rand_score, weight_matrix)

print (upodated_total)

[[ 96.8   85.8   66.5 ]
 [101.2   84.7   67.45]
 [ 95.7   77.    66.5 ]
 [ 82.5   77.    66.5 ]
 [ 77.   102.3   77.9 ]
 [ 95.7   82.5   87.4 ]
 [ 89.1  102.3   75.05]
 [ 86.9   77.    69.35]
 [ 86.9   96.8   89.3 ]
 [ 77.    79.2   69.35]
 [102.3   77.    74.1 ]
 [107.8   81.4   93.1 ]
 [ 77.    81.4   91.2 ]
 [ 82.5  103.4   66.5 ]
 [ 83.6  103.4   68.4 ]
 [ 77.    91.3   73.15]
 [ 86.9   84.7   68.4 ]
 [ 92.4   99.    66.5 ]
 [ 77.   102.3   68.4 ]
 [ 84.7   99.    79.8 ]]


In [46]:
# Question 2
# a)
x = np.array([[7, 1, 1, 1], [1,3,3,3]])

def median_and_mode (x):
    median = np.median (x)
    mode = np.bincount(x.flat).argmax()

    print ('Median is:', median)
    print ('Mode is:', mode)

print (median_and_mode(x))


Median is: 2.0
Mode is: 1
None
