In [49]:
import numpy as np

rand_score = 60 + 40*np.random.rand (20,3)
rand_score = rand_score.astype (int)

print (rand_score)


[[66 64 73]
 [95 85 71]
 [99 89 61]
 [87 63 73]
 [63 97 93]
 [69 71 93]
 [61 62 69]
 [80 72 61]
 [92 99 64]
 [65 79 99]
 [64 86 61]
 [80 66 78]
 [97 66 96]
 [74 61 63]
 [87 92 63]
 [60 67 83]
 [83 83 80]
 [99 98 81]
 [70 82 67]
 [74 89 90]]


In [64]:
# Q1 

# a)
ave_column = np.mean (rand_score, axis=0)
ave_row = np.mean (rand_score, axis=1)
print (ave_column)
print (ave_row)



[78.25 78.55 75.95]
[67.66666667 83.66666667 83.         74.33333333 84.33333333 77.66666667
 64.         71.         85.         81.         70.33333333 74.66666667
 86.33333333 66.         80.66666667 70.         82.         92.66666667
 73.         84.33333333]


In [65]:
# b)
max_score = np.max (rand_score, axis=0)
min_score = np.min (rand_score, axis=0)
print (min_score)

[60 61 61]


In [66]:
# c)
ave_first_two = np.mean (rand_score[0:2], axis=1)
ave_last_two = np.mean (rand_score[18:20], axis=1)

print (ave_first_two)
print (ave_last_two)

[67.66666667 83.66666667]
[73.         84.33333333]


In [67]:
# d)
ave_Mid_first10 = np.mean (rand_score[0:10,0:2], axis=1)
print (ave_Mid_first10)

[65.  90.  94.  75.  80.  70.  61.5 76.  95.5 72. ]


In [78]:
# e)
list_70 = np.where (rand_score < 70)
row_70, col_70 = list_70[0], list_70[1]

for i,j in zip (row_70, col_70):
    print (i,j)

0 0
0 1
2 2
3 1
4 0
5 0
6 0
6 1
6 2
7 2
8 2
9 0
10 0
10 2
11 1
12 1
13 1
13 2
14 2
15 0
15 1
18 2
